/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleshipika;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Acek
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniJudul = new javax.swing.JLabel();
        jbPlay = new javax.swing.JLabel();
        jbHelp = new javax.swing.JLabel();
        jbHigh = new javax.swing.JLabel();
        jbExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniJudul.setFont(new java.awt.Font("Rosewood Std Regular", 1, 60)); // NOI18N
        iniJudul.setForeground(new java.awt.Color(0, 0, 0));
        iniJudul.setText("BATTLESHIP");
        getContentPane().add(iniJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jbPlay.setFont(new java.awt.Font("Mesquite Std", 0, 40)); // NOI18N
        jbPlay.setForeground(new java.awt.Color(0, 0, 0));
        jbPlay.setText("PLAY");
        jbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbPlayMouseExited(evt);
            }
        });
        getContentPane().add(jbPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        jbHelp.setFont(new java.awt.Font("Mesquite Std", 0, 40)); // NOI18N
        jbHelp.setForeground(new java.awt.Color(0, 0, 0));
        jbHelp.setText("HELP");
        jbHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbHelpMouseExited(evt);
            }
        });
        getContentPane().add(jbHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        jbHigh.setFont(new java.awt.Font("Mesquite Std", 0, 40)); // NOI18N
        jbHigh.setForeground(new java.awt.Color(0, 0, 0));
        jbHigh.setText("HIGH SCORE");
        jbHigh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbHighMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbHighMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbHighMouseExited(evt);
            }
        });
        getContentPane().add(jbHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jbExit.setFont(new java.awt.Font("Mesquite Std", 0, 40)); // NOI18N
        jbExit.setForeground(new java.awt.Color(0, 0, 0));
        jbExit.setText("EXIT");
        jbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbExitMouseExited(evt);
            }
        });
        getContentPane().add(jbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bacground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlayMouseClicked
        // TODO add your handling code here:
        new Awal().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbPlayMouseClicked

    private void jbPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlayMouseEntered
        // TODO add your handling code here:
        jbPlay.setForeground(Color.white);
    }//GEN-LAST:event_jbPlayMouseEntered

    private void jbPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlayMouseExited
        // TODO add your handling code here:
        jbPlay.setForeground(Color.black);
    }//GEN-LAST:event_jbPlayMouseExited

    private void jbHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHelpMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ini help", "what's battleship?", 1);
    }//GEN-LAST:event_jbHelpMouseClicked

    private void jbHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHelpMouseEntered
        // TODO add your handling code here:
        jbHelp.setForeground(Color.white);
    }//GEN-LAST:event_jbHelpMouseEntered

    private void jbHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHelpMouseExited
        // TODO add your handling code here:
        jbHelp.setForeground(Color.black);
    }//GEN-LAST:event_jbHelpMouseExited

    private void jbHighMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHighMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ini high score");
    }//GEN-LAST:event_jbHighMouseClicked

    private void jbHighMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHighMouseEntered
        // TODO add your handling code here:
        jbHigh.setForeground(Color.white);
    }//GEN-LAST:event_jbHighMouseEntered

    private void jbHighMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHighMouseExited
        // TODO add your handling code here:
        jbHigh.setForeground(Color.black);
    }//GEN-LAST:event_jbHighMouseExited

    private void jbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(rootPane, "Confirm to exit", "EXIT GAME", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbExitMouseClicked

    private void jbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseEntered
        // TODO add your handling code here:
        jbExit.setForeground(Color.white);
    }//GEN-LAST:event_jbExitMouseEntered

    private void jbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExitMouseExited
        // TODO add your handling code here:
        jbExit.setForeground(Color.black);
    }//GEN-LAST:event_jbExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iniJudul;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jbExit;
    private javax.swing.JLabel jbHelp;
    private javax.swing.JLabel jbHigh;
    private javax.swing.JLabel jbPlay;
    // End of variables declaration//GEN-END:variables
}
